# TCL File Generated by Component Editor 7.2 on:
# Mon Feb 27 18:26:11 EST 2012
# DO NOT MODIFY

set_source_file ""
set_module "cpu_jtag_debug_module"
set_module_description ""
set_module_property "className" "cpu_jtag_debug_module"
set_module_property "group" ""
set_module_property "libraries" [ list "altera.altera_europa_support_lib.all" "ieee.std_logic_1164.all" "ieee.std_logic_arith.all" "ieee.std_logic_unsigned.all" "std.standard.all" ]

# Module parameters
